apiVersion: v1
kind: Service
metadata:
  name: ci-cd-app-service
  labels:
    app: ci-cd
spec:
  type: NodePort
  selector:
    app: ci-cd
  ports:
    - port: 80            # Port exposed by the service
      targetPort: 80      # Port the container is listening on
      nodePort: 30080     # Port on the Node (between 30000–32767)
